name: Pipeline

on: [push, pull_request]

jobs:
  quality:
    name: Qualiry Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
      - run: npm run build
